import type { Metadata, Viewport } from "next";
import { Fraunces, DM_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import AnimatedDotGrid from "@/components/AnimatedDotGrid";
import MotionProvider from "@/components/MotionProvider";

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
  variable: "--font-fraunces",
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-dm-sans",
  display: "swap",
});

const SITE_URL = "https://thembangobeni.vercel.app";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  alternates: { canonical: SITE_URL },
  title: {
    default: "Themba Ngobeni · Java Developer",
    template: "%s · Themba Ngobeni",
  },
  description:
    "Java developer at FNB working on cross-border payments: TCIB for the SADC region, SWIFT MT to ISO 20022, and Spring Boot services in production.",
  keywords: [
    "Java Developer",
    "Spring Boot",
    "Backend Engineer",
    "Microservices",
    "Software Engineer",
    "Cross-border payments",
    "ISO 20022",
    "SWIFT",
    "Johannesburg",
    "South Africa",
  ],
  authors: [{ name: "Themba Ngobeni", url: SITE_URL }],
  creator: "Themba Ngobeni",
  openGraph: {
    type: "website",
    url: SITE_URL,
    title: "Themba Ngobeni · Java Developer",
    description:
      "Java developer at FNB, working on cross-border payments for the SADC region: TCIB, the SWIFT MT to ISO 20022 migration, and the Spring Boot API that feeds a live fraud detection model.",
    siteName: "Themba Ngobeni",
    locale: "en_ZA",
    // Social card image is generated by app/opengraph-image.tsx (1200x630).
  },
  twitter: {
    card: "summary_large_image",
    title: "Themba Ngobeni · Java Developer",
    description:
      "Java developer at FNB working on cross-border payments: TCIB, ISO 20022 and Spring Boot services.",
    // Twitter card image is generated by app/twitter-image.tsx (falls back to OG).
  },
  robots: {
    index: true,
    follow: true,
  },
  // Proves ownership of the site to Google Search Console. Public by design:
  // it only matters alongside the Google account that added the property.
  verification: { google: "ULFbdJhfBEitz_tMUTKhYhPF4Jd_djdfz7uPjTo14z0" },
};

export const viewport: Viewport = {
  themeColor: "#0a0a0a",
  width: "device-width",
  initialScale: 1,
};

const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Themba Ngobeni",
  url: SITE_URL,
  jobTitle: "Java Developer",
  worksFor: { "@type": "Organization", name: "First National Bank (FNB)" },
  alumniOf: {
    "@type": "CollegeOrUniversity",
    name: "University of the Witwatersrand",
  },
  address: {
    "@type": "PostalAddress",
    addressLocality: "Johannesburg",
    addressCountry: "ZA",
  },
  email: "mailto:thembatman0@gmail.com",
  sameAs: [
    "https://github.com/ThembaTman0",
    "https://www.linkedin.com/in/themba-ngobeni-6a163b164/",
  ],
  knowsAbout: [
    "Java",
    "Spring Boot",
    "Microservices",
    "REST APIs",
    "Cross-border payments",
    "ISO 20022",
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${dmSans.variable}`}
      // The head script below adds classes before React hydrates.
      suppressHydrationWarning
    >
      <head>
        {/* Animated content is server-rendered in its hidden start state.
            Before first paint, mark that JavaScript is running (.js); if the
            app still hasn't hydrated after 2.5s (slow or failed scripts), add
            .reveal-all. The safety net in globals.css shows every data-reveal
            element when .js is missing or .reveal-all is present. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){var d=document.documentElement;d.classList.add('js');setTimeout(function(){if(!window.__motionReady)d.classList.add('reveal-all')},2500)})();",
          }}
        />
      </head>
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />

        <a href="#main-content" className="skip-link">
          Skip to content
        </a>

        <AnimatedDotGrid />
        <div id="scroll-progress" />
        <MotionProvider>
          <Navbar />
          <main id="main-content">{children}</main>
          <Footer />
        </MotionProvider>

        {/* Scroll progress bar (anchor smooth-scroll is handled by CSS
            scroll-behavior + scroll-padding-top in globals.css) */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                var bar = document.getElementById('scroll-progress');
                if (!bar) return;
                window.addEventListener('scroll', function () {
                  var total = document.documentElement.scrollHeight - window.innerHeight;
                  var pct = total > 0 ? Math.min(window.scrollY / total, 1) : 0;
                  bar.style.transform = 'scaleX(' + pct + ')';
                }, { passive: true });
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
